### ISSUE TITLE
本地启动报错

### ISSUE THREAD

**Issue by MrKingHH** [Moon-Future/ktv-system#1]
Proxy error: Could not proxy request /user/login from localhost:8080 to http://127.0.0.1:8889.
![image](https://user-images.githubusercontent.com/22386359/103986034-02a97800-51c5-11eb-8aaf-5b729f645883.png)
楼主能抽空看下是什么原因吗？

**Comment by MrKingHH** [comment]
![image](https://user-images.githubusercontent.com/22386359/103986149-31bfe980-51c5-11eb-9a92-e8193c3f8b12.png)
数据库配置已修改。

**Comment by Moon-Future** [comment]
> Proxy error: Could not proxy request /user/login from localhost:8080 to http://127.0.0.1:8889.
> ![image](https://user-images.githubusercontent.com/22386359/103986034-02a97800-51c5-11eb-8aaf-5b729f645883.png)
> 楼主能抽空看下是什么原因吗？

这看着是没启动后端吧？我重新clone试了下，不启动后端会报这个错

**Comment by MrKingHH** [comment]
后端怎么启动呢？我没用Node.js做过后端。—_—

**Comment by Moon-Future** [comment]
...进入sevrv文件夹，node index.js 启动，可能会报错，没有 secret.js 文件，要创建一下

**Comment by MrKingHH** [comment]
OK，我现在可以跑起来了。这个地方的`code != rootCode[type]`为什么写两遍？
![image](https://user-images.githubusercontent.com/22386359/104079083-2f5c9e80-525c-11eb-9e8a-7fa88425e614.png)

**Comment by MrKingHH** [comment]
你这个注册功能有个Bug，填写验证码的地方，前端没有获取到数据，一直提醒请输入验证码。
Longin.vue中的`formData: {
          account: '', password: '', rePassword: '', name: '', code: ''
        },`增加一个`code:''`就可以了。

**Comment by Moon-Future** [comment]
嗯，code 忘加了，rootCode[type] 写重了😅
