### ISSUE TITLE
test.ktv.cl8023.com 打不开

### ISSUE THREAD

**Issue by gooking** [Moon-Future/ktv-system#6]
test.ktv.cl8023.com 打不开

想来学习一下，可惜打不开，大神能不能修复一下？

**Comment by Moon-Future** [comment]
> 



> test.ktv.cl8023.com 打不开
> 
> 想来学习一下，可惜打不开，大神能不能修复一下？

已重新部署~

**Comment by gooking** [comment]
感谢
